Repository didymo/OnkoDICOM, pull requests merged in 2020-12, with the labels that each got.

#84 Workaround pymedphys anonymise api changes
  src/Model/Anon.py
Labels: enhancement

#85 workaround for pymedphys: strip the UTC information from AcquisitionDateTime in place
  src/Model/Anon.py
Labels: enhancement

#87 check for presence of WindowWidth and WindowCenter before accessing
  legacy/src/View/mainpage/MainPage.py
  src/Model/InitialModel.py
Labels: bug

#88 Improved feedback when modifying RTSTRUCT
  src/Model/ROI.py
  src/View/mainpage/DeleteROIWindow.py
  src/View/mainpage/DrawROIWindow.py
  src/View/mainpage/RenameROIWindow.py
Labels: redmine-ticket
