Repository didymo/OnkoDICOM, pull requests merged in 2025-09, with the labels that each got.

#353 Mouse Adjustments + Better DICOM compatability
  res/images/btn-icons/rotate_arrow_icon.png
  res/images/btn-icons/translate_arrow_icon.png
  res/stylesheet-win-linux.qss
  res/stylesheet.qss
  src/Model/VTKEngine.py
  src/View/ImageFusion/BaseViewerGUI.py
  src/View/ImageFusion/ImageFusionAxialView.py
  src/View/ImageFusion/TranslateRotateMenu.py
  src/View/mainpage/DicomGraphicsScene.py
Labels: enhancement, redmine-ticket, python

#373 Update to stylesheets, Made StyleSheetReader Singleton
  res/stylesheet-win-linux.qss
  res/stylesheet.qss
  src/Controller/ActionHandler.py
  src/View/StyleSheetReader.py
  src/View/mainpage/MenuBar.py
Labels: bug, python

#379 Re Implementation of Draw ROI
  res/stylesheet-win-linux.qss
  src/Controller/ActionHandler.py
  src/Controller/ROIOptionsController.py
  src/View/ImageFusion/BaseViewerGUI.py
  src/View/ImageFusion/ImageFusionAxialView.py
  src/View/ImageFusion/TranslateRotateMenu.py
  src/View/mainpage/ClinicalDataView.py
  src/View/mainpage/DicomView.py
  src/View/mainpage/DrawROIWindow/ButtonBox.py
  src/View/mainpage/DrawROIWindow/Canvas.py
  src/View/mainpage/DrawROIWindow/ConvertToDicom.py
  src/View/mainpage/DrawROIWindow/CopyRoi.py
  src/View/mainpage/DrawROIWindow/DrawBoundingBox.py
  src/View/mainpage/DrawROIWindow/DrawROIInitialiser.py
  src/View/mainpage/DrawROIWindow/Drawing.py
  src/View/mainpage/DrawROIWindow/MultiLayerConturePopup.py
  src/View/mainpage/DrawROIWindow/ROINameButton.py
  src/View/mainpage/DrawROIWindow/SaveROIProgressWindow.py
  src/View/mainpage/DrawROIWindow/SaveToRTSS.py
  src/View/mainpage/DrawROIWindow/ScrollLoader.py
  src/View/mainpage/DrawROIWindow/SelectROIPopUp.py
  src/View/mainpage/DrawROIWindow/Toolbar.py
  src/View/mainpage/DrawROIWindow/Transect_Window.py
  src/View/mainpage/DrawROIWindow/UIDrawROIWindow.py
  src/View/mainpage/DrawROIWindow/UnitsBox.py
  src/View/mainpage/DrawROIWindow/dicom_utils.py
  test/test_view_dicom_view.py
  test/test_view_drawing.py
Labels: enhancement, redmine-ticket, python

#380 Auto Segment name remapping from csv, data validation and checks, fix index out of range error
  src/Controller/AutoSegmentationController.py
  src/Controller/RTStructFileLoader.py
  src/Model/NiftiToRtstructConverter.py
  src/View/mainpage/StructureTab.py
Labels: bug, enhancement, python
